---
# TODO: integrate basic outline in the comments to service both RedHat and Debian
# file: roles/common/tasks/main.yml
#
# - name: be sure ntp is installed
#   yum: pkg=ntp state=installed
#     tags: ntp
#
#     - name: be sure ntp is configured
#       template: src=ntp.conf.j2 dest=/etc/ntp.conf
#         notify:
#             - restart ntpd
#               tags: ntp
#
#               - name: be sure ntpd is running and enabled
#                 service: name=ntpd state=running enabled=yes
#                   tags: ntp
  - name: NTP - Install ntp package for RHEL
    yum: name=ntp state=latest
    when: ansible_os_family == 'RedHat'
    notify:
     - restart ntpd

  - name: NTP - Ensure ntpd service
    service: name=ntpd state=started enabled=yes
    when: ansible_os_family == 'RedHat'
  
  - name: NTP - Copy the ntp.conf template file
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    notify:
     - restart ntpd
