---

- name: Start snmpd to initialize setup account
  service:
    name: 'snmpd'
    state: 'started'

- name: Clear old usm config
  shell: "[ -f /var/net-snmp/snmpd.conf ] && echo > /var/net-snmp/snmpd.conf || :" 

- name: Create snmp3 account
  command: /usr/bin/snmpusm -v3 -u initial -n "" -l authPriv
           -a MD5 -A example -x DES -X example
           localhost create "{{ snmp_usm_user }}" initial

- name: Change snmp3 account password
  command: /usr/bin/snmpusm -v3 -u initial -n "" -l authPriv
           -a MD5 -A example -x DES -X example -Ca -Cx
           localhost passwd example "{{ snmp_usm_pass }}" "{{ snmp_usm_user }}"

